name: "Get Milestone Data"
description: 'Get Milestones Data'
inputs:
  repository:
    description: "repository name"
    required: true
outputs:
  data:
    description: "Milestones data JSON"
runs:
  using: 'node16'
  main: 'index.js'